# Generated by Django 3.2 on 2021-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
