# Generated by Django 3.2 on 2021-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0002_alter_visitor_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.DateTimeField(unique=True, verbose_name='date published'),
        ),
    ]
