# Generated by Django 3.2 on 2021-04-10 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0003_alter_time_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
    ]
