# Generated by Django 3.2 on 2021-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0004_time_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='identifier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('identifier', 'time')},
        ),
    ]
