# Generated by Django 3.2 on 2021-04-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrator', '0005_auto_20210410_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['identifier']},
        ),
    ]
